# Generated by Django 5.2.17 on 2026-10-01 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin (Full Control)"),
                    ("registrar", "Registrar (Data Owner)"),
                    ("dept_head", "Department Head / Lecturer"),
                    ("student", "Student (Stretch Goal)"),
                    ("analyst", "Data Analyst (Legacy)"),
                    ("faculty", "Faculty / Researcher (Legacy)"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("UPLOAD", "Dataset Upload"),
                            ("DELETE_UPLOAD", "Delete Upload & Rollback"),
                            ("USER_CREATE", "Create User"),
                            ("USER_UPDATE", "Update User"),
                            ("USER_DEACTIVATE", "Deactivate User"),
                            ("USER_ACTIVATE", "Activate User"),
                            ("PASSWORD_RESET", "Reset Password"),
                            ("DEPT_CREATE", "Create Department"),
                            ("DEPT_UPDATE", "Update Department"),
                            ("DEPT_DELETE", "Delete Department"),
                            ("PROGRAM_CREATE", "Create Program"),
                            ("PROGRAM_DELETE", "Delete Program"),
                            ("COURSE_CREATE", "Create Course"),
                            ("COURSE_DELETE", "Delete Course"),
                            ("EXPORT_CSV", "Export Scoped CSV"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
