# Generated by Django 5.2.17 on 2026-10-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_phone_alter_userprofile_role_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin (Full Control)"),
                    ("registrar", "Registrar (Data Owner)"),
                    ("dept_head", "Department Head / Lecturer"),
                    ("student", "Student (Stretch Goal)"),
                    ("analyst", "Data Analyst (Legacy)"),
                    ("faculty", "Faculty / Researcher (Legacy)"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
