version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: unidata_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portal_db
      POSTGRES_USER: portal_user
      POSTGRES_PASSWORD: portal_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: unidata_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: unidata_web
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_demo &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-portal-production-secret-key-992384
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - DATABASE_URL=postgres://portal_user:portal_password@db:5432/portal_db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: unidata_celery
    restart: unless-stopped
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - SECRET_KEY=django-insecure-portal-production-secret-key-992384
      - DATABASE_URL=postgres://portal_user:portal_password@db:5432/portal_db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  media_volume:
