# Generated by Django 5.2.17 on 2026-10-01 01:52

import apps.uploads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "stored_file",
                    models.FileField(upload_to=apps.uploads.models.upload_path_handler),
                ),
                (
                    "cleaned_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.uploads.models.cleaned_path_handler,
                    ),
                ),
                (
                    "cleaned_csv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.uploads.models.cleaned_path_handler,
                    ),
                ),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        default="Upload queued for processing", max_length=255
                    ),
                ),
                ("progress_pct", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("row_count_raw", models.IntegerField(default=0)),
                ("row_count_clean", models.IntegerField(default=0)),
                ("col_count_raw", models.IntegerField(default=0)),
                ("col_count_clean", models.IntegerField(default=0)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("config_options", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("header_row", models.IntegerField(default=0)),
                ("n_rows", models.IntegerField(default=0)),
                ("n_cols", models.IntegerField(default=0)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="uploads.upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_json", models.JSONField(default=dict)),
                ("correlation_json", models.JSONField(default=dict)),
                ("quality_score", models.FloatField(default=0.0)),
                ("completeness_score", models.FloatField(default=0.0)),
                ("validity_score", models.FloatField(default=0.0)),
                ("uniqueness_score", models.FloatField(default=0.0)),
                ("consistency_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="uploads.upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColumnProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_raw", models.CharField(max_length=200)),
                ("name_clean", models.CharField(max_length=200)),
                ("inferred_type", models.CharField(max_length=50)),
                ("role", models.CharField(default="text", max_length=50)),
                ("missing_pct_before", models.FloatField(default=0.0)),
                ("missing_pct_after", models.FloatField(default=0.0)),
                ("n_unique", models.IntegerField(default=0)),
                ("unique_sample", models.JSONField(blank=True, default=list)),
                ("min_val", models.FloatField(blank=True, null=True)),
                ("max_val", models.FloatField(blank=True, null=True)),
                ("mean_val", models.FloatField(blank=True, null=True)),
                ("std_val", models.FloatField(blank=True, null=True)),
                ("median_val", models.FloatField(blank=True, null=True)),
                ("iqr_val", models.FloatField(blank=True, null=True)),
                ("skew_val", models.FloatField(blank=True, null=True)),
                ("kurt_val", models.FloatField(blank=True, null=True)),
                ("outlier_count", models.IntegerField(default=0)),
                ("normality_test", models.CharField(blank=True, max_length=150)),
                ("normality_hint", models.TextField(blank=True)),
                (
                    "sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uploads.sheet",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_profiles",
                        to="uploads.upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CleaningAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet", models.CharField(default="Sheet1", max_length=150)),
                ("rule_id", models.CharField(max_length=20)),
                ("rule_name", models.CharField(max_length=100)),
                ("column", models.CharField(blank=True, max_length=200)),
                ("row_ref", models.IntegerField(blank=True, null=True)),
                ("before_value", models.TextField(blank=True)),
                ("after_value", models.TextField(blank=True)),
                ("reason", models.TextField()),
                ("severity", models.CharField(default="info", max_length=20)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="uploads.upload",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
