# Generated by Django 5.2.17 on 2026-10-01 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uploads", "0002_upload_dataset_type_upload_inserted_rows_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. STAT, CS, MATH", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department head or primary coordinator",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. BS-STAT, MS-DS", max_length=30, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("Undergraduate", "Undergraduate"),
                            ("Graduate", "Graduate"),
                            ("Postgraduate", "Postgraduate"),
                        ],
                        default="Undergraduate",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="academic.department",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. STA308, CS101", max_length=30, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("credits", models.IntegerField(default=3)),
                ("semester", models.CharField(default="Fall 2026", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload record this course was imported from (for rollbacks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_records",
                        to="uploads.upload",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="academic.department",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="academic.program",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="e.g. STU1001", max_length=30, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cohort", models.CharField(default="2024", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Graduated", "Graduated"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Active",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="academic.department",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academic.program",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload record this student was imported from (for rollbacks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_records",
                        to="uploads.upload",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional login account for student self-service portal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["student_id"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Late", "Late"),
                            ("Excused", "Excused"),
                        ],
                        default="Present",
                        max_length=20,
                    ),
                ),
                ("session_topic", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload record this attendance was imported from (for rollbacks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="uploads.upload",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academic.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "course__code"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(default="Fall 2026", max_length=50)),
                ("numerical_score", models.FloatField()),
                ("letter_grade", models.CharField(blank=True, max_length=5)),
                ("gpa_points", models.FloatField(default=0.0)),
                ("passed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academic.course",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload record this grade was imported from (for rollbacks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_records",
                        to="uploads.upload",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-semester", "course__code"],
                "unique_together": {("student", "course", "semester")},
            },
        ),
    ]
